### ISSUE TITLE
Correct city name

### ISSUE THREAD

**Issue by sergiy-talashko** [JamesMilnerUK/github-map#3]
I don't know why in _global-city-population-estimates_ **Lviv** in Ukraine is called as **Lvov**, but correct name is **Lviv**

[https://en.wikipedia.org/wiki/Lviv](https://en.wikipedia.org/wiki/Lviv)
[Google Map](https://www.google.co.uk/maps/place/Lviv,+Lvivska,+Ukraine/@49.8327786,23.9421962,12z/data=!3m1!4b1!4m5!3m4!1s0x473add7c09109a57:0x4223c517012378e2!8m2!3d49.8379825!4d24.0270996?hl=en)

**Comment by JamesLMilner** [comment]
Thanks, I'll correct it :)

**Comment by sergiy-talashko** [comment]
@JamesMilnerUK Thank you.

**Comment by JamesLMilner** [comment]
Should be fixed now so I'm closing. Cheers!
