### ISSUE TITLE
Not real data

### ISSUE THREAD

**Issue by sergey-alekseev** [JamesMilnerUK/github-map#4]
Some big cities that for sure have many github users show super low amounts. E.g.
![screen shot 2016-09-19 at 15 05 44](https://cloud.githubusercontent.com/assets/2371639/18631487/efa19c0a-7e7a-11e6-90db-3f73f0cab086.png)

Where do you get data from?

**Comment by JamesLMilner** [comment]
Unfortunately some cities have many different names which means that they get missed off the scraping process of the GitHub API. That is the combined total of "Tel Aviv-Yafo" and "Tel Aviv-Jaffa". However when we just search [Tel Aviv](https://github.com/search?utf8=%E2%9C%93&q=location%3A%22tel+aviv%22&type=Users&ref=advsearch&l=&l=) we get 1,182 results. If you like you can make a pull request. If not I will try to find the time to correct it later.

**Comment by JamesLMilner** [comment]
I'd eventually like to get all these fixed, so if you spot any more please let me know. Thanks!

**Comment by sergey-alekseev** [comment]
@JamesMilnerUK great! Will look later and help you with those. I like the map. About to share on FB, but needed more trust to the data.

**Comment by sergey-alekseev** [comment]
@JamesMilnerUK I looked into other cities and did not find anything suspicious. However local naming may be an issue as well – e.g. "Minsk" (in English) and "Минск" (in Russian). A local names amount is low though.  
OK, now I feel free to share your map 👍 😃

**Comment by JamesLMilner** [comment]
Should be fixed now so I'm closing! Thanks
